//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public int Id { get; set; }
        public int FundoID { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Rendimento { get; set; }
    
        public virtual Fundo Fundo { get; set; }
    }
}
